### ISSUE TITLE
Listagem de um Cliente por meio do método findById (GET)

### ISSUE THREAD

**Issue by natycavaillier** [natycavaillier/helpr#1]
- [x] Criar Controlador Rest
- [x] Criar o Serviço de Cliente
- [x] Criar métodos para o Endpoint de RestController
- [x] Vincular os repositórios de cliente
- [x] Testar endpoint no postman

**Comment by soulcode-acad** [comment]
Que trabalho profissional, código limpo perfeitamente organizado e estruturado. Entregas impecáveis e bem interligadas trabalho fino irretocável. Fora todo o esforço de ajudar e indicar impecável meus parabéns achamos outro Almir!

![image](https://user-images.githubusercontent.com/100297907/172934815-854dc8ea-22ec-4cb8-b464-633fcc2311f7.png)
